// Basil POS reconciliation & file import (PRD 7.4): import CSV/file exports
// generated by Basil to cross-reference line items (by ISBN + order id) and
// perform automated batch status updates, e.g. "Ordered" -> "Received".
//
// Basil doesn't expose a documented public export schema we can integrate
// against sight-unseen, so this ships as a clearly-labeled MOCK: it accepts
// a CSV shaped like a plausible Basil PO-received export, and includes a
// sample-data generator so the import flow is testable end-to-end today.
// Swap `parseBasilCsv` for real column mapping once you have a sample
// export from Basil in hand.

import Papa from "papaparse";
import type { LineItemStatus } from "@/lib/domain/status";

export type BasilImportRow = {
  orderItemId: number | null;
  isbn13: string;
  basilPoNumber: string;
  newStatus: LineItemStatus;
  raw: Record<string, string>;
};

export type BasilImportResult = {
  rows: BasilImportRow[];
  errors: string[];
};

const BASIL_STATUS_MAP: Record<string, LineItemStatus> = {
  ordered: "ordered",
  backordered: "backordered",
  received: "received",
  "checked in": "received",
  fulfilled: "fulfilled",
  cancelled: "cancelled",
  canceled: "cancelled",
};

/** Parses a Basil-style CSV export into normalized rows ready for batch status updates. */
export function parseBasilCsv(csvText: string): BasilImportResult {
  const parsed = Papa.parse<Record<string, string>>(csvText, {
    header: true,
    skipEmptyLines: true,
  });

  const errors: string[] = parsed.errors.map(
    (e) => `Row ${e.row ?? "?"}: ${e.message}`
  );

  const rows: BasilImportRow[] = parsed.data.map((raw) => {
    const statusRaw = (raw["Status"] ?? raw["status"] ?? "").trim().toLowerCase();
    const orderItemIdRaw = raw["OrderItemID"] ?? raw["order_item_id"] ?? "";
    return {
      orderItemId: orderItemIdRaw ? Number(orderItemIdRaw) : null,
      isbn13: (raw["ISBN13"] ?? raw["isbn"] ?? "").trim(),
      basilPoNumber: (raw["PO Number"] ?? raw["po_number"] ?? "").trim(),
      newStatus: BASIL_STATUS_MAP[statusRaw] ?? "ordered",
      raw,
    };
  });

  return { rows, errors };
}

export function isBasilMockEnabled(): boolean {
  return process.env.BASIL_MOCK !== "false";
}

/** Generates a sample Basil export CSV for demoing/testing the import flow. */
export function generateSampleBasilCsv(
  items: { orderItemId: number; isbn13: string; poNumber: string }[]
): string {
  return Papa.unparse({
    fields: ["OrderItemID", "ISBN13", "PO Number", "Status"],
    data: items.map((i) => [i.orderItemId, i.isbn13, i.poNumber, "Received"]),
  });
}
